export const listTools = [
  {
    id: 1,
    gambar: "/assets/tools/vscode.png",
    nama: "Visual Studio Code",
    ket: "Code Editor",
    dad: "100",
  },
  {
    id: 2,
    gambar: "/assets/tools/reactjs.png",
    nama: "React JS",
    ket: "Framework",
    dad: "200",
  },
  {
    id: 4,
    gambar: "/assets/tools/tailwind.png",
    nama: "Tailwind CSS",
    ket: "Framework",
    dad: "400",
  },
  {
    id: 5,
    gambar: "/assets/tools/bootstrap.png",
    nama: "Bootstrap",
    ket: "Framework",
    dad: "500",
  },
  {
    id: 6,
    gambar: "/assets/tools/js.png",
    nama: "Javascript",
    ket: "Language",
    dad: "600",
  },
  {
    id: 7,
    gambar: "/assets/tools/nodejs.png",
    nama: "Node JS",
    ket: "Javascript Runtime",
    dad: "700",
  },
  {
    id: 8,
    gambar: "/assets/tools/github.png",
    nama: "Github",
    ket: "Repository",
    dad: "800",
  },
  {
    id: 10,
    gambar: "/assets/tools/canva.png",
    nama: "Canva",
    ket: "Design App",
    dad: "1000",
  },
  {
    id: 11,
    gambar: "/assets/tools/figma.png",
    nama: "Figma",
    ket: "Design App",
    dad: "1100",
  },
  {
    id: 13,
    gambar: "/assets/tools/firebase.png",
    nama: "Firebase",
    ket: "Backend",
    dad: "1300",
  },
  {
    id: 14,
    gambar: "/assets/tools/html.png",
    nama: "HTML",
    ket: "Language",
    dad: "1400",
  },
  {
    id: 15,
    gambar: "/assets/tools/css.png",
    nama: "CSS",
    ket: "Language",
    dad: "1500",
  },
  {
    id: 17,
    gambar: "/assets/tools/php.png",
    nama: "PHP",
    ket: "Language",
    dad: "1700",
  },
  {
    id: 18,
    gambar: "/assets/tools/vite.png",
    nama: "Vite",
    ket: "Build Tool",
    dad: "1800",
  },
  {
    id: 19,
    gambar: "/assets/tools/mysql.png",
    nama: "MySql",
    ket: "Database",
    dad: "1900",
  },
];

export const listProyek = [];

