export const listTools = [
  {
    id: 1,
    gambar: "/assets/tools/vscode.png",
    nama: "Visual Studio Code",
    ket: "Code Editor",
    dad: "100",
  },
  {
    id: 2,
    gambar: "/assets/tools/reactjs.png",
    nama: "React JS",
    ket: "Framework",
    dad: "200",
  },
  {
    id: 4,
    gambar: "/assets/tools/tailwind.png",
    nama: "Tailwind CSS",
    ket: "Framework",
    dad: "400",
  },
  {
    id: 5,
    gambar: "/assets/tools/bootstrap.webp",
    nama: "Bootstrap",
    ket: "Framework",
    dad: "500",
  },
  {
    id: 6,
    gambar: "/assets/tools/js.png",
    nama: "Javascript",
    ket: "Language",
    dad: "600",
  },
  {
    id: 7,
    gambar: "/assets/tools/nodejs.png",
    nama: "Node JS",
    ket: "Javascript Runtime",
    dad: "700",
  },
  {
    id: 8,
    gambar: "/assets/tools/github.png",
    nama: "Github",
    ket: "Repository",
    dad: "800",
  },
  {
    id: 10,
    gambar: "/assets/tools/canva.webp",
    nama: "Canva",
    ket: "Design App",
    dad: "1000",
  },
  {
    id: 11,
    gambar: "/assets/tools/figma.webp",
    nama: "Figma",
    ket: "Design App",
    dad: "1100",
  },
  {
    id: 13,
    gambar: "/assets/tools/firebase.webp",
    nama: "Firebase",
    ket: "Backend",
    dad: "1300",
  },
  {
    id: 14,
    gambar: "/assets/tools/html.webp",
    nama: "HTML",
    ket: "Language",
    dad: "1400",
  },
  {
    id: 15,
    gambar: "/assets/tools/css.webp",
    nama: "CSS",
    ket: "Language",
    dad: "1500",
  },
  {
    id: 17,
    gambar: "/assets/tools/php.webp",
    nama: "PHP",
    ket: "Language",
    dad: "1700",
  },
  {
    id: 18,
    gambar: "/assets/tools/vite.webp",
    nama: "Vite",
    ket: "Build Tool",
    dad: "1800",
  },
  {
    id: 19,
    gambar: "/assets/tools/mysql.webp",
    nama: "MySql",
    ket: "Database",
    dad: "1900",
  },
  {
    id: 20,
    gambar: "/assets/tools/laravel.svg",
    nama: "Laravel",
    ket: "Framework",
    dad: "2000",
  },
  {
    id: 21,
    gambar: "/assets/tools/vuejs.svg",
    nama: "Vue JS",
    ket: "Framework",
    dad: "2100",
  },
  {
    id: 22,
    gambar: "/assets/tools/inertia.svg",
    nama: "Inertia.js",
    ket: "Full-Stack Bridge",
    dad: "2200",
  },
  {
    id: 23,
    gambar: "/assets/tools/cloudflare.svg",
    nama: "Cloudflare",
    ket: "CDN / DNS",
    dad: "2300",
  },
  {
    id: 24,
    gambar: "/assets/tools/stripe.svg",
    nama: "Stripe",
    ket: "Pagos",
    dad: "2400",
  },
  {
    id: 25,
    gambar: "/assets/tools/resend.svg",
    nama: "Resend",
    ket: "Email API",
    dad: "2500",
  },
  {
    id: 26,
    gambar: "/assets/tools/leaflet.svg",
    nama: "Leaflet",
    ket: "Mapas interactivos",
    dad: "2600",
  },
  {
    id: 27,
    gambar: "/assets/tools/typescript.svg",
    nama: "TypeScript",
    ket: "Language",
    dad: "2700",
  },
  {
    id: 28,
    gambar: "/assets/tools/git.svg",
    nama: "Git",
    ket: "Control de versiones",
    dad: "2800",
  },
  {
    id: 29,
    gambar: "/assets/tools/aws.svg",
    nama: "AWS",
    ket: "Cloud / Hosting",
    dad: "2900",
  },
  {
    id: 30,
    gambar: "/assets/tools/docker.svg",
    nama: "Docker",
    ket: "Contenedores",
    dad: "3000",
  },
  {
    id: 31,
    gambar: "/assets/tools/googleanalytics.svg",
    nama: "Google Analytics",
    ket: "Analítica web",
    dad: "3100",
  },
  {
    id: 32,
    gambar: "/assets/tools/postman.svg",
    nama: "Postman",
    ket: "Testing de APIs",
    dad: "3200",
  },
  {
    id: 33,
    gambar: "/assets/tools/sass.svg",
    nama: "Sass",
    ket: "Preprocesador CSS",
    dad: "3300",
  },
];

export const listProyek = [
  {
    image: "https://opengraph.githubassets.com/1/airamfuentes/rustikan",
    title: "Rustikan",
    subtitle: "Plataforma de comercio local y sostenible en Lanzarote",
    handle: "#Laravel · #Vue3 · #Inertia",
    location: "Lanzarote, España",
    borderColor: "#7c3aed",
    gradient: "linear-gradient(135deg, #1e1b2e 0%, #2d1b4e 50%, #0f172a 100%)",
    fullDescription:
      "Rustikan es una plataforma de marketplace y entrega de comida local que conecta productores, agricultores y artesanos de Lanzarote con consumidores. Incluye sistema de pagos con Stripe y Rusticoin (moneda propia), seguimiento de pedidos, chat en vivo, panel de productor, panel de almacén y panel de administración. Desarrollada con Laravel 12, Vue 3, Inertia.js, Tailwind CSS y MySQL. Multilingüe: español, inglés, francés, alemán e italiano.",
    url: "https://github.com/airamfuentes/rustikan",
  },
];

